name: Cypress Tests
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build project
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Uploading artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
